services:
  - type: web
    name: ai-code-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
    healthCheckPath: /health
    
  - type: static
    name: ai-code-detection-frontend
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 