services:
  - type: web
    name: ai-code-detection-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    
  - type: static
    name: ai-code-detection-frontend
    buildCommand: echo "Static site ready"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 