"""
AI Code Detection Bot - Advanced detection of AI-generated code.

This package provides tools for analyzing code to determine if it was likely
generated by AI systems like ChatGPT, GitHub Copilot, etc.
"""

__version__ = "1.0.0"
__author__ = "AI Detection Bot Team"
__email__ = "support@aidetectionbot.com"

from .core.detector import AICodeDetector
from .core.analyzer import CodeAnalyzer
from .core.patterns import PatternMatcher
from .models.result import DetectionResult, AnalysisReport

__all__ = [
    "AICodeDetector",
    "CodeAnalyzer", 
    "PatternMatcher",
    "DetectionResult",
    "AnalysisReport",
] 